version: '3'
services:
    server:
        image: wtf_server
        build: ./server
        command: npm start
        restart: unless-stopped
        ports:
            - 3000:3000
        environment: 
            PORT: 3000
        volumes:
            - ./server/src:/app/src/

    # client:
    #     image: wtf_client
    #     build: ./client
    #     command: npm start
    #     restart: unless-stopped
    #     ports:
    #         - 9000:9000
    #     environment: 
    #         PORT: 9000
    #     volumes:
    #         - ./client/src:/app/src/
    #     depends_on:
    #         - server
