version: '3'
services:
    server:
        image: wtf_server
        build: ./server
        command: npm test
        restart: unless-stopped
        ports:
            - 3000:3000
        environment: 
            PORT: 3000
        volumes:
            - ./server/src:/app/src/
